# Configuration for Travis CI
language: java
matrix:
  fast_finish: true
  include:
  - env: IMAGE=maven:3-jdk-11 JDOC=Y
  - env: IMAGE=maven:3-jdk-10
  - env: IMAGE=maven:3-jdk-9
  - env: IMAGE=maven:3-jdk-8 JDOC=Y
branches:
  only:
    - master
env:
  global:
  - DOCKERRUN="docker run -it --rm -v $PWD:/src -v $HOME/.m2:/root/.m2 -w /src"
services:
- docker
before_install:
- docker pull $IMAGE
install:
# Print the Maven version, skip tests and javadoc
- $DOCKERRUN $IMAGE mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Djavax.net.ssl.trustStorePassword=changeit -B -V
script:
# Print surefire output to the console instead of files
- unset _JAVA_OPTIONS
- if [ $JDOC = "Y" ]; then export JDOC=javadoc:javadoc; fi
- $DOCKERRUN $IMAGE mvn -Dcheckstyle.skip -Dsurefire.useFile=false -Dsurefire.threadCount=1 -Dsurefire.perCoreThreadCount=false -Djavax.net.ssl.trustStorePassword=changeit test $JDOC
git:
  depth: 10000
sudo: required
cache:
  directories:
  - $HOME/.m2
# End .travis.yml
