# Configuration for Appveyor CI
version: '{build}'
image: Visual Studio 2017
clone_depth: 10000
# branches to build
branches:
  # whitelist
  only:
  - master
  - new-master
  - javadoc
  - /^branch-.*$/
  - /^[0-9]+-.*$/
matrix:
  fast_finish: true
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files\Java\jdk10
build_script:
- mvn clean -V install -DskipTests -Dmaven.javadoc.skip=true -Djavax.net.ssl.trustStorePassword=changeit
test_script:
- mvn -Dsurefire.useFile=false -Djavax.net.ssl.trustStorePassword=changeit verify javadoc:javadoc javadoc:test-javadoc
cache:
- C:\maven\
- C:\Users\appveyor\.m2
# End .appveyor.yml
